//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/DB_Base.proto
namespace PDB_Base
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DBAccount")]
  public partial class DBAccount : global::ProtoBuf.IExtensible
  {
    public DBAccount() {}
    
    private ulong _ulid = default(ulong);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ulid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong ulid
    {
      get { return _ulid; }
      set { _ulid = value; }
    }
    private ulong _uluid = default(ulong);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"uluid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong uluid
    {
      get { return _uluid; }
      set { _uluid = value; }
    }
    private string _sacc = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sacc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sacc
    {
      get { return _sacc; }
      set { _sacc = value; }
    }
    private string _spwd = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"spwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string spwd
    {
      get { return _spwd; }
      set { _spwd = value; }
    }
    private string _stel = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"stel", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string stel
    {
      get { return _stel; }
      set { _stel = value; }
    }
    private string _swx = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"swx", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string swx
    {
      get { return _swx; }
      set { _swx = value; }
    }
    private string _sqq = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sqq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sqq
    {
      get { return _sqq; }
      set { _sqq = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}