// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common_Base.proto

package PCommon_Base;

public final class CommonBase {
  private CommonBase() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code PCommon_Base.ETest}
   */
  public enum ETest
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Test1 = 0;</code>
     */
    Test1(0),
    /**
     * <code>Test2 = 1;</code>
     */
    Test2(1),
    /**
     * <code>Test3 = 2;</code>
     */
    Test3(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Test1 = 0;</code>
     */
    public static final int Test1_VALUE = 0;
    /**
     * <code>Test2 = 1;</code>
     */
    public static final int Test2_VALUE = 1;
    /**
     * <code>Test3 = 2;</code>
     */
    public static final int Test3_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ETest valueOf(int value) {
      return forNumber(value);
    }

    public static ETest forNumber(int value) {
      switch (value) {
        case 0: return Test1;
        case 1: return Test2;
        case 2: return Test3;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ETest>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ETest> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ETest>() {
            public ETest findValueByNumber(int number) {
              return ETest.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return PCommon_Base.CommonBase.getDescriptor().getEnumTypes().get(0);
    }

    private static final ETest[] VALUES = values();

    public static ETest valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ETest(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PCommon_Base.ETest)
  }

  public interface NetHeadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PCommon_Base.NetHead)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int32 Cmd = 1;</code>
     */
    int getCmd();

    /**
     * <pre>
     *包编号
     * </pre>
     *
     * <code>int32 Index = 2;</code>
     */
    int getIndex();

    /**
     * <pre>
     *包总数
     * </pre>
     *
     * <code>int32 Count = 3;</code>
     */
    int getCount();

    /**
     * <pre>
     *数据长度
     * </pre>
     *
     * <code>int32 DataLength = 4;</code>
     */
    int getDataLength();

    /**
     * <pre>
     *服务器下发的key，key不正确不处理
     * </pre>
     *
     * <code>int32 key = 5;</code>
     */
    int getKey();
  }
  /**
   * Protobuf type {@code PCommon_Base.NetHead}
   */
  public  static final class NetHead extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PCommon_Base.NetHead)
      NetHeadOrBuilder {
    // Use NetHead.newBuilder() to construct.
    private NetHead(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NetHead() {
      cmd_ = 0;
      index_ = 0;
      count_ = 0;
      dataLength_ = 0;
      key_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NetHead(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              cmd_ = input.readInt32();
              break;
            }
            case 16: {

              index_ = input.readInt32();
              break;
            }
            case 24: {

              count_ = input.readInt32();
              break;
            }
            case 32: {

              dataLength_ = input.readInt32();
              break;
            }
            case 40: {

              key_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PCommon_Base.CommonBase.internal_static_PCommon_Base_NetHead_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PCommon_Base.CommonBase.internal_static_PCommon_Base_NetHead_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PCommon_Base.CommonBase.NetHead.class, PCommon_Base.CommonBase.NetHead.Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    private int cmd_;
    /**
     * <pre>
     *消息id
     * </pre>
     *
     * <code>int32 Cmd = 1;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    public static final int INDEX_FIELD_NUMBER = 2;
    private int index_;
    /**
     * <pre>
     *包编号
     * </pre>
     *
     * <code>int32 Index = 2;</code>
     */
    public int getIndex() {
      return index_;
    }

    public static final int COUNT_FIELD_NUMBER = 3;
    private int count_;
    /**
     * <pre>
     *包总数
     * </pre>
     *
     * <code>int32 Count = 3;</code>
     */
    public int getCount() {
      return count_;
    }

    public static final int DATALENGTH_FIELD_NUMBER = 4;
    private int dataLength_;
    /**
     * <pre>
     *数据长度
     * </pre>
     *
     * <code>int32 DataLength = 4;</code>
     */
    public int getDataLength() {
      return dataLength_;
    }

    public static final int KEY_FIELD_NUMBER = 5;
    private int key_;
    /**
     * <pre>
     *服务器下发的key，key不正确不处理
     * </pre>
     *
     * <code>int32 key = 5;</code>
     */
    public int getKey() {
      return key_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (cmd_ != 0) {
        output.writeInt32(1, cmd_);
      }
      if (index_ != 0) {
        output.writeInt32(2, index_);
      }
      if (count_ != 0) {
        output.writeInt32(3, count_);
      }
      if (dataLength_ != 0) {
        output.writeInt32(4, dataLength_);
      }
      if (key_ != 0) {
        output.writeInt32(5, key_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cmd_);
      }
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, index_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, count_);
      }
      if (dataLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, dataLength_);
      }
      if (key_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, key_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PCommon_Base.CommonBase.NetHead)) {
        return super.equals(obj);
      }
      PCommon_Base.CommonBase.NetHead other = (PCommon_Base.CommonBase.NetHead) obj;

      boolean result = true;
      result = result && (getCmd()
          == other.getCmd());
      result = result && (getIndex()
          == other.getIndex());
      result = result && (getCount()
          == other.getCount());
      result = result && (getDataLength()
          == other.getDataLength());
      result = result && (getKey()
          == other.getKey());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (37 * hash) + DATALENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getDataLength();
      hash = (37 * hash) + KEY_FIELD_NUMBER;
      hash = (53 * hash) + getKey();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PCommon_Base.CommonBase.NetHead parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PCommon_Base.CommonBase.NetHead parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.NetHead parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PCommon_Base.CommonBase.NetHead parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.NetHead parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PCommon_Base.CommonBase.NetHead parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.NetHead parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PCommon_Base.CommonBase.NetHead parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.NetHead parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PCommon_Base.CommonBase.NetHead parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.NetHead parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PCommon_Base.CommonBase.NetHead parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PCommon_Base.CommonBase.NetHead prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PCommon_Base.NetHead}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PCommon_Base.NetHead)
        PCommon_Base.CommonBase.NetHeadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PCommon_Base.CommonBase.internal_static_PCommon_Base_NetHead_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PCommon_Base.CommonBase.internal_static_PCommon_Base_NetHead_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PCommon_Base.CommonBase.NetHead.class, PCommon_Base.CommonBase.NetHead.Builder.class);
      }

      // Construct using PCommon_Base.CommonBase.NetHead.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cmd_ = 0;

        index_ = 0;

        count_ = 0;

        dataLength_ = 0;

        key_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PCommon_Base.CommonBase.internal_static_PCommon_Base_NetHead_descriptor;
      }

      public PCommon_Base.CommonBase.NetHead getDefaultInstanceForType() {
        return PCommon_Base.CommonBase.NetHead.getDefaultInstance();
      }

      public PCommon_Base.CommonBase.NetHead build() {
        PCommon_Base.CommonBase.NetHead result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PCommon_Base.CommonBase.NetHead buildPartial() {
        PCommon_Base.CommonBase.NetHead result = new PCommon_Base.CommonBase.NetHead(this);
        result.cmd_ = cmd_;
        result.index_ = index_;
        result.count_ = count_;
        result.dataLength_ = dataLength_;
        result.key_ = key_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PCommon_Base.CommonBase.NetHead) {
          return mergeFrom((PCommon_Base.CommonBase.NetHead)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PCommon_Base.CommonBase.NetHead other) {
        if (other == PCommon_Base.CommonBase.NetHead.getDefaultInstance()) return this;
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.getDataLength() != 0) {
          setDataLength(other.getDataLength());
        }
        if (other.getKey() != 0) {
          setKey(other.getKey());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PCommon_Base.CommonBase.NetHead parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PCommon_Base.CommonBase.NetHead) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int cmd_ ;
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int32 Cmd = 1;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int32 Cmd = 1;</code>
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息id
       * </pre>
       *
       * <code>int32 Cmd = 1;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }

      private int index_ ;
      /**
       * <pre>
       *包编号
       * </pre>
       *
       * <code>int32 Index = 2;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <pre>
       *包编号
       * </pre>
       *
       * <code>int32 Index = 2;</code>
       */
      public Builder setIndex(int value) {
        
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *包编号
       * </pre>
       *
       * <code>int32 Index = 2;</code>
       */
      public Builder clearIndex() {
        
        index_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <pre>
       *包总数
       * </pre>
       *
       * <code>int32 Count = 3;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <pre>
       *包总数
       * </pre>
       *
       * <code>int32 Count = 3;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *包总数
       * </pre>
       *
       * <code>int32 Count = 3;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private int dataLength_ ;
      /**
       * <pre>
       *数据长度
       * </pre>
       *
       * <code>int32 DataLength = 4;</code>
       */
      public int getDataLength() {
        return dataLength_;
      }
      /**
       * <pre>
       *数据长度
       * </pre>
       *
       * <code>int32 DataLength = 4;</code>
       */
      public Builder setDataLength(int value) {
        
        dataLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *数据长度
       * </pre>
       *
       * <code>int32 DataLength = 4;</code>
       */
      public Builder clearDataLength() {
        
        dataLength_ = 0;
        onChanged();
        return this;
      }

      private int key_ ;
      /**
       * <pre>
       *服务器下发的key，key不正确不处理
       * </pre>
       *
       * <code>int32 key = 5;</code>
       */
      public int getKey() {
        return key_;
      }
      /**
       * <pre>
       *服务器下发的key，key不正确不处理
       * </pre>
       *
       * <code>int32 key = 5;</code>
       */
      public Builder setKey(int value) {
        
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *服务器下发的key，key不正确不处理
       * </pre>
       *
       * <code>int32 key = 5;</code>
       */
      public Builder clearKey() {
        
        key_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PCommon_Base.NetHead)
    }

    // @@protoc_insertion_point(class_scope:PCommon_Base.NetHead)
    private static final PCommon_Base.CommonBase.NetHead DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PCommon_Base.CommonBase.NetHead();
    }

    public static PCommon_Base.CommonBase.NetHead getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NetHead>
        PARSER = new com.google.protobuf.AbstractParser<NetHead>() {
      public NetHead parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NetHead(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NetHead> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NetHead> getParserForType() {
      return PARSER;
    }

    public PCommon_Base.CommonBase.NetHead getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MTest1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:PCommon_Base.MTest1)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 a = 1;</code>
     */
    int getA();

    /**
     * <code>int32 b = 2;</code>
     */
    int getB();
  }
  /**
   * Protobuf type {@code PCommon_Base.MTest1}
   */
  public  static final class MTest1 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PCommon_Base.MTest1)
      MTest1OrBuilder {
    // Use MTest1.newBuilder() to construct.
    private MTest1(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MTest1() {
      a_ = 0;
      b_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MTest1(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              a_ = input.readInt32();
              break;
            }
            case 16: {

              b_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PCommon_Base.CommonBase.internal_static_PCommon_Base_MTest1_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PCommon_Base.CommonBase.internal_static_PCommon_Base_MTest1_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PCommon_Base.CommonBase.MTest1.class, PCommon_Base.CommonBase.MTest1.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private int a_;
    /**
     * <code>int32 a = 1;</code>
     */
    public int getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    private int b_;
    /**
     * <code>int32 b = 2;</code>
     */
    public int getB() {
      return b_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != 0) {
        output.writeInt32(1, a_);
      }
      if (b_ != 0) {
        output.writeInt32(2, b_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      if (b_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, b_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PCommon_Base.CommonBase.MTest1)) {
        return super.equals(obj);
      }
      PCommon_Base.CommonBase.MTest1 other = (PCommon_Base.CommonBase.MTest1) obj;

      boolean result = true;
      result = result && (getA()
          == other.getA());
      result = result && (getB()
          == other.getB());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + getA();
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + getB();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PCommon_Base.CommonBase.MTest1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PCommon_Base.CommonBase.MTest1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.MTest1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PCommon_Base.CommonBase.MTest1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.MTest1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PCommon_Base.CommonBase.MTest1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.MTest1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PCommon_Base.CommonBase.MTest1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.MTest1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PCommon_Base.CommonBase.MTest1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.MTest1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PCommon_Base.CommonBase.MTest1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PCommon_Base.CommonBase.MTest1 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PCommon_Base.MTest1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PCommon_Base.MTest1)
        PCommon_Base.CommonBase.MTest1OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PCommon_Base.CommonBase.internal_static_PCommon_Base_MTest1_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PCommon_Base.CommonBase.internal_static_PCommon_Base_MTest1_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PCommon_Base.CommonBase.MTest1.class, PCommon_Base.CommonBase.MTest1.Builder.class);
      }

      // Construct using PCommon_Base.CommonBase.MTest1.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        a_ = 0;

        b_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PCommon_Base.CommonBase.internal_static_PCommon_Base_MTest1_descriptor;
      }

      public PCommon_Base.CommonBase.MTest1 getDefaultInstanceForType() {
        return PCommon_Base.CommonBase.MTest1.getDefaultInstance();
      }

      public PCommon_Base.CommonBase.MTest1 build() {
        PCommon_Base.CommonBase.MTest1 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PCommon_Base.CommonBase.MTest1 buildPartial() {
        PCommon_Base.CommonBase.MTest1 result = new PCommon_Base.CommonBase.MTest1(this);
        result.a_ = a_;
        result.b_ = b_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PCommon_Base.CommonBase.MTest1) {
          return mergeFrom((PCommon_Base.CommonBase.MTest1)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PCommon_Base.CommonBase.MTest1 other) {
        if (other == PCommon_Base.CommonBase.MTest1.getDefaultInstance()) return this;
        if (other.getA() != 0) {
          setA(other.getA());
        }
        if (other.getB() != 0) {
          setB(other.getB());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PCommon_Base.CommonBase.MTest1 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PCommon_Base.CommonBase.MTest1) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int a_ ;
      /**
       * <code>int32 a = 1;</code>
       */
      public int getA() {
        return a_;
      }
      /**
       * <code>int32 a = 1;</code>
       */
      public Builder setA(int value) {
        
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 a = 1;</code>
       */
      public Builder clearA() {
        
        a_ = 0;
        onChanged();
        return this;
      }

      private int b_ ;
      /**
       * <code>int32 b = 2;</code>
       */
      public int getB() {
        return b_;
      }
      /**
       * <code>int32 b = 2;</code>
       */
      public Builder setB(int value) {
        
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 b = 2;</code>
       */
      public Builder clearB() {
        
        b_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PCommon_Base.MTest1)
    }

    // @@protoc_insertion_point(class_scope:PCommon_Base.MTest1)
    private static final PCommon_Base.CommonBase.MTest1 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PCommon_Base.CommonBase.MTest1();
    }

    public static PCommon_Base.CommonBase.MTest1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MTest1>
        PARSER = new com.google.protobuf.AbstractParser<MTest1>() {
      public MTest1 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MTest1(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MTest1> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MTest1> getParserForType() {
      return PARSER;
    }

    public PCommon_Base.CommonBase.MTest1 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MTest2OrBuilder extends
      // @@protoc_insertion_point(interface_extends:PCommon_Base.MTest2)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 a = 2;</code>
     */
    int getA();

    /**
     * <code>int32 b = 3;</code>
     */
    int getB();
  }
  /**
   * Protobuf type {@code PCommon_Base.MTest2}
   */
  public  static final class MTest2 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PCommon_Base.MTest2)
      MTest2OrBuilder {
    // Use MTest2.newBuilder() to construct.
    private MTest2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MTest2() {
      a_ = 0;
      b_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MTest2(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 16: {

              a_ = input.readInt32();
              break;
            }
            case 24: {

              b_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PCommon_Base.CommonBase.internal_static_PCommon_Base_MTest2_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PCommon_Base.CommonBase.internal_static_PCommon_Base_MTest2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PCommon_Base.CommonBase.MTest2.class, PCommon_Base.CommonBase.MTest2.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 2;
    private int a_;
    /**
     * <code>int32 a = 2;</code>
     */
    public int getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 3;
    private int b_;
    /**
     * <code>int32 b = 3;</code>
     */
    public int getB() {
      return b_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != 0) {
        output.writeInt32(2, a_);
      }
      if (b_ != 0) {
        output.writeInt32(3, b_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, a_);
      }
      if (b_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, b_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PCommon_Base.CommonBase.MTest2)) {
        return super.equals(obj);
      }
      PCommon_Base.CommonBase.MTest2 other = (PCommon_Base.CommonBase.MTest2) obj;

      boolean result = true;
      result = result && (getA()
          == other.getA());
      result = result && (getB()
          == other.getB());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + getA();
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + getB();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PCommon_Base.CommonBase.MTest2 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PCommon_Base.CommonBase.MTest2 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.MTest2 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PCommon_Base.CommonBase.MTest2 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.MTest2 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PCommon_Base.CommonBase.MTest2 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.MTest2 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PCommon_Base.CommonBase.MTest2 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.MTest2 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PCommon_Base.CommonBase.MTest2 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PCommon_Base.CommonBase.MTest2 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PCommon_Base.CommonBase.MTest2 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PCommon_Base.CommonBase.MTest2 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PCommon_Base.MTest2}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PCommon_Base.MTest2)
        PCommon_Base.CommonBase.MTest2OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PCommon_Base.CommonBase.internal_static_PCommon_Base_MTest2_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PCommon_Base.CommonBase.internal_static_PCommon_Base_MTest2_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PCommon_Base.CommonBase.MTest2.class, PCommon_Base.CommonBase.MTest2.Builder.class);
      }

      // Construct using PCommon_Base.CommonBase.MTest2.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        a_ = 0;

        b_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PCommon_Base.CommonBase.internal_static_PCommon_Base_MTest2_descriptor;
      }

      public PCommon_Base.CommonBase.MTest2 getDefaultInstanceForType() {
        return PCommon_Base.CommonBase.MTest2.getDefaultInstance();
      }

      public PCommon_Base.CommonBase.MTest2 build() {
        PCommon_Base.CommonBase.MTest2 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PCommon_Base.CommonBase.MTest2 buildPartial() {
        PCommon_Base.CommonBase.MTest2 result = new PCommon_Base.CommonBase.MTest2(this);
        result.a_ = a_;
        result.b_ = b_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PCommon_Base.CommonBase.MTest2) {
          return mergeFrom((PCommon_Base.CommonBase.MTest2)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PCommon_Base.CommonBase.MTest2 other) {
        if (other == PCommon_Base.CommonBase.MTest2.getDefaultInstance()) return this;
        if (other.getA() != 0) {
          setA(other.getA());
        }
        if (other.getB() != 0) {
          setB(other.getB());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PCommon_Base.CommonBase.MTest2 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PCommon_Base.CommonBase.MTest2) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int a_ ;
      /**
       * <code>int32 a = 2;</code>
       */
      public int getA() {
        return a_;
      }
      /**
       * <code>int32 a = 2;</code>
       */
      public Builder setA(int value) {
        
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 a = 2;</code>
       */
      public Builder clearA() {
        
        a_ = 0;
        onChanged();
        return this;
      }

      private int b_ ;
      /**
       * <code>int32 b = 3;</code>
       */
      public int getB() {
        return b_;
      }
      /**
       * <code>int32 b = 3;</code>
       */
      public Builder setB(int value) {
        
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 b = 3;</code>
       */
      public Builder clearB() {
        
        b_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:PCommon_Base.MTest2)
    }

    // @@protoc_insertion_point(class_scope:PCommon_Base.MTest2)
    private static final PCommon_Base.CommonBase.MTest2 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PCommon_Base.CommonBase.MTest2();
    }

    public static PCommon_Base.CommonBase.MTest2 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MTest2>
        PARSER = new com.google.protobuf.AbstractParser<MTest2>() {
      public MTest2 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MTest2(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MTest2> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MTest2> getParserForType() {
      return PARSER;
    }

    public PCommon_Base.CommonBase.MTest2 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PCommon_Base_NetHead_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PCommon_Base_NetHead_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PCommon_Base_MTest1_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PCommon_Base_MTest1_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PCommon_Base_MTest2_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PCommon_Base_MTest2_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Common_Base.proto\022\014PCommon_Base\"U\n\007Net" +
      "Head\022\013\n\003Cmd\030\001 \001(\005\022\r\n\005Index\030\002 \001(\005\022\r\n\005Coun" +
      "t\030\003 \001(\005\022\022\n\nDataLength\030\004 \001(\005\022\013\n\003key\030\005 \001(\005" +
      "\"\036\n\006MTest1\022\t\n\001a\030\001 \001(\005\022\t\n\001b\030\002 \001(\005\"\036\n\006MTes" +
      "t2\022\t\n\001a\030\002 \001(\005\022\t\n\001b\030\003 \001(\005*(\n\005ETest\022\t\n\005Tes" +
      "t1\020\000\022\t\n\005Test2\020\001\022\t\n\005Test3\020\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_PCommon_Base_NetHead_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PCommon_Base_NetHead_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PCommon_Base_NetHead_descriptor,
        new java.lang.String[] { "Cmd", "Index", "Count", "DataLength", "Key", });
    internal_static_PCommon_Base_MTest1_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PCommon_Base_MTest1_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PCommon_Base_MTest1_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_PCommon_Base_MTest2_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PCommon_Base_MTest2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PCommon_Base_MTest2_descriptor,
        new java.lang.String[] { "A", "B", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
