/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.PDB_Option.EDB_CMD');

/**
 * @enum {number}
 */
proto.PDB_Option.EDB_CMD = {
  DB_CMD_NONE: 0,
  GD_GET_DBACCOUNT: 202,
  DG_GET_DBACCOUNT: 203,
  GD_CREATE_DBACCOUNT: 204,
  DG_CREATE_DBACCOUNT: 205,
  GD_UPDATE_DBACCOUNT: 206,
  DG_UPDATE_DBACCOUNT: 207,
  GD_DELETE_DBACCOUNT: 208,
  DG_DELETE_DBACCOUNT: 209,
  GD_GET_DBUSERINFO: 210,
  DG_GET_DBUSERINFO: 211,
  GD_CREATE_DBUSERINFO: 212,
  DG_CREATE_DBUSERINFO: 213,
  GD_UPDATE_DBUSERINFO: 214,
  DG_UPDATE_DBUSERINFO: 215,
  GD_DELETE_DBUSERINFO: 216,
  DG_DELETE_DBUSERINFO: 217
};

